### PR TITLE
Change default exposure, adjust a few examples

### PR DESCRIPTION
**Pull request by GitGhillie**
(edit: all examples adjusted now)

Want to see if I'm on the right track before going all in 😅 
Adjusted 3d_scene, load_gltf, lighting and skybox examples.

Let me know if comparison screenshots would help

### CODE REVIEW

**Comment by JMS55** [comment]
Thanks so much for doing this! All 4 look good to me :)

**Comment by GitGhillie** [comment]
I'll update this comment with my progress 😃 

100% of examples adjusted:
3d	3d_gizmos
3d	3d_scene
3d	3d_shapes
3d	3d_viewport_to_world
3d	anti_aliasing
3d	atmospheric_fog
3d	blend_modes
3d	bloom_3d
3d	deferred_rendering
3d	fog
3d	generate_custom_mesh
3d	lighting
3d	lines
3d	load_gltf
3d	orthographic
3d	parallax_mapping
3d	parenting
3d	pbr
3d	render_to_texture
3d	shadow_biases
3d	shadow_caster_receiver
3d	skybox
3d	spherical_area_lights
3d	split_screen
3d	spotlight
3d	ssao
3d	tonemapping
3d	transmission
3d	transparency_3d
3d	two_passes
3d	update_gltf_scene
3d	vertex_colors
3d	wireframe
animation	animated_fox
animation	animated_transform
animation	cubic_curve
animation	custom_skinned_mesh
animation	gltf_skinned_mesh
animation	morph_targets
audio	spatial_audio_3d
ecs	iter_combinations
games	alien_cake_addict
mobile	bevy_mobile_example
shader	array_texture
shader	extended_material
shader	post_processing
shader	shader_material_screenspace_texture
shader	shader_prepass
stress_tests	many_cubes
stress_tests	many_foxes
stress_tests	many_lights
tools	scene_viewer
transforms	3d_rotation
transforms	scale
transforms	transform
transforms	translation
window	low_power
window	multiple_windows
window	screenshot

**Comment by JMS55** [comment]
Btw coreh fixed the transmission example in case you missed it: https://github.com/GitGhillie/bevy/pull/1. Thanks for all the great progress!

**Comment by GitGhillie** [comment]
Ah yeah thanks I missed it. That's one more down!

**Comment by GitGhillie** [comment]
Done. I will write some notes in the [main PR](https://github.com/bevyengine/bevy/pull/8407#issuecomment-1877222055)

**Comment by coreh** [comment]
Fixed the atmospheric fog example: https://github.com/GitGhillie/bevy/pull/2

**Comment by JMS55** [comment]
Thanks for all the work! I'll have to rebase this PR, some stuff with environment maps changed recently. Then we can see about getting this merged into bevy proper.

**Pull request merged**
