### PR TITLE
Fix dx12 shader miscompilation with jimenez temporal pcf

### PR DESCRIPTION
**Pull request by Elabajaba**
I checked and it compiles and works on both dx12 and vulkan.

### CODE REVIEW

**Comment by Elabajaba** [comment]
`let else` formatting check killing the ci run :|

**Review by JMS55 — COMMENTED** [review]
Can you replace vec2<f32>() with just vec()? Also, can you open an issue with naga please?

**Comment by Elabajaba** [comment]
> Can you replace vec2() with just vec()?

I don't think that works in wgsl?

> Also, can you open an issue with naga please?

Yeah, I've just gotta check with a smaller reproduction first to make sure it's naga and not a naga_oil bug.

**Comment by JMS55** [comment]
Sorry, meant vec2(). Also github ate my formatting, I meant `vec2<f32>() -> vec2()`.

**Pull request merged**
